name: Workino App Production and Preview Action CI
run-name: Workino action number ${{github.run_number}}

on:
  push:
    branches:
      - "development"

jobs:
  #? JOB 1 :- Setup the app before push it to testing

  setups:
    runs-on: ubuntu-latest
    name: Setup the App
    defaults:
      run:
        working-directory: ./Workino-Frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.9.0"

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{secrets.EXPO_TOKEN}}

      - name: Message
        run: echo "All DONEğŸ‘ğŸ»ğŸŒ¿ğŸŠ"

        #? JOB 2 :- Test the app using expo-doctor before push it to production

  test:
    runs-on: ubuntu-latest
    name: Test the Application
    defaults:
      run:
        working-directory: Workino-Frontend
    needs: setups
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Inspect
        run: |
          ls
          pwd
          cd ..
          ls
          pwd
          cd ..
          ls
          pwd

      - name: Install EAS
        run: npm install -g eas-cli

      - name: Installing dependencies
        run: npm install

      - name: EAS Doctor
        run: npx expo-doctor@latest

        #? JOB 3 :- Build and Deploy Job

  # build_deploy:
  #   runs-on: ubuntu-latest
  #   name: Build and Deploy
  #   defaults:
  #     run:
  #       working-directory: Workino-Frontend
  #   needs: test
  #   steps:
  #     - name: Build
  #       run: |
  #         eas build --platform android --profile development --non-interactive --no-wait --message "Build"

  #     - name: Check build list
  #       run: eas build:list
